# \#72 City travel
If you won't walk or cycle, then are you more likely to drive or take public transportation? If we restrict the question to how people get to work, then we can probably get clearer results, and perhaps even learn something about how different cities operate.

A recent article in the Economist (https://www.economist.com/interactive/2024-walkable-cities) summarized a recent paper in the journal Science by researchers Rafael Prieto-Curiel and Juan P. Ospina. Their paper, "The ABC of mobility" (https://www.sciencedirect.com/science/article/pii/S0160412024001272), looks at the "modal share" for three different types of transportation in a city – active (walking/biking), public transportation, and driving. The researchers collected many studies about transportation and work, from a wide variety of cities, in order to understand each city. They then looked at other factors to consider for a given city, such as income, population, and location in the world.

I should add that the "ABC" in the title refers to the three types of mobility that the researchers discuss:
- A stands for "active," and includes walking and biking
- B stands for "bus," and is the overall category for public transportation
- C stands for "car," and describes people who drive to work

They found, not surprisingly, that cities in North America rely on cars more than in the rest of the world.

Even in New York, a city in which people famously walk and use public transportation quite a lot, many people still commute by car. A proposal to charge drivers extra if they go to the most-congested parts of Manhattan during peak hours was about to go into effect on June 30th, but New York Governor Kathy Hochul suspended the plan earlier this month (https://www.nytimes.com/2024/06/05/nyregion/congestion-pricing-pause-hochul.html?unlocked_article_code=1.2k0.xMmn.a7Q2Lxo3J885&smid=url-share), reducing the incentive to use public transportation while simultaneously adding a $1 billion hole to the public transportation budget.

## Data and seven questions
The data is available at https://github.com/rafaelprietocuriel/ModalShare/blob/main/ModalShare.csv

## Challenges
The learning goal include multi indexes, grouping, pivot table, and plotting among others.

- Import the CSV file into a data frame. We'll want a three-part multi-index from the region, Country, and City columns.
- How many distinct cities were represented in this research? Which 10 cities were surveyed the most times?

In [23]:
import pandas as pd

df = pd.read_csv('ModalShare.csv')
df = df.set_index(['region', 'Country', 'City'])
df

                                                CityID   ObsID  year  \
region                Country        City
Europe                Germany        Aachen     M10001  ID0005  2003
                                     Aachen     M10001  ID0004  2017
                      Denmark        Aarhus     M10002  ID0008  2004
                      United Kingdom Aberdeen   M10003  ID0009  2008
North America         United States  Abilene    M10004    C001  2019
...                                                ...     ...   ...
East Asia and Pacific China          Zhuzhou    M10877  ID0745  2018
                                     Wenzhou    M10878  ID0746  2018
                                     Zhongshan  M10879  ID0747  2018
                                     Zibo       M10880  ID0748  2018
                                     Yantai     M10881  ID0749  2018

                                               LastObservation  \
region                Country        City
Europe                Germany        Aachen                 NO
                                     Aachen                YES
                      Denmark        Aarhus                YES
                      United Kingdom Aberdeen              YES
North America         United States  Abilene               YES
...                                                        ...
East Asia and Pacific China          Zhuzhou               YES
                                     Wenzhou               YES
                                     Zhongshan             YES
                                     Zibo                  YES
                                     Yantai                YES

                                                           metro_names  \
region                Country        City
Europe                Germany        Aachen                     Aachen
                                     Aachen                     Aachen
                      Denmark        Aarhus                     Aarhus
                      United Kingdom Aberdeen                 Aberdeen
North America         United States  Abilene    Abilene, TX Metro Area
...                                                                ...
East Asia and Pacific China          Zhuzhou                   Zhuzhou
                                     Wenzhou                   Wenzhou
                                     Zhongshan               Zhongshan
                                     Zibo                         Zibo
                                     Yantai                     Yantai

                                                    continent  \
region                Country        City
Europe                Germany        Aachen            Europe
                                     Aachen            Europe
                      Denmark        Aarhus            Europe
                      United Kingdom Aberdeen          Europe
North America         United States  Abilene    North America
...                                                       ...
East Asia and Pacific China          Zhuzhou             Asia
                                     Wenzhou             Asia
                                     Zhongshan           Asia
                                     Zibo                Asia
                                     Yantai              Asia

                                                       subregion state_name  \
region                Country        City
Europe                Germany        Aachen       Western Europe        NaN
                                     Aachen       Western Europe        NaN
                      Denmark        Aarhus      Northern Europe        NaN
                      United Kingdom Aberdeen    Northern Europe        NaN
North America         United States  Abilene    Northern America      Texas
...                                                          ...        ...
East Asia and Pacific China          Zhuzhou        Eastern Asia        NaN
                                     Wenzhou        Eastern Asia        NaN
                                     Zhongshan      Eastern Asia        NaN
                                     Zibo           Eastern Asia        NaN
                                     Yantai         Eastern Asia        NaN

                                               state_abbr  population  ...  \
region                Country        City                              ...
Europe                Germany        Aachen           NaN      256605  ...
                                     Aachen           NaN      256605  ...
                      Denmark        Aarhus           NaN      331000  ...
                      United Kingdom Aberdeen         NaN      211000  ...
North America         United States  Abilene           TX      164878  ...
...                                                   ...         ...  ...
East Asia and Pacific China          Zhuzhou          NaN     4890000  ...
                                     Wenzhou          NaN     1500000  ...
                                     Zhongshan        NaN     7600000  ...
                                     Zibo             NaN     2100000  ...
                                     Yantai           NaN     4740000  ...

                                                 Walking   Cycling  \
region                Country        City
Europe                Germany        Aachen     0.240000  0.100000
                                     Aachen     0.297030  0.108911
                      Denmark        Aarhus     0.072917  0.281250
                      United Kingdom Aberdeen   0.297030  0.019802
North America         United States  Abilene         NaN       NaN
...                                                  ...       ...
East Asia and Pacific China          Zhuzhou         NaN       NaN
                                     Wenzhou         NaN       NaN
                                     Zhongshan       NaN       NaN
                                     Zibo            NaN       NaN
                                     Yantai          NaN       NaN

                                                Motorbykes    Active  \
region                Country        City
Europe                Germany        Aachen            NaN  0.340000
                                     Aachen            NaN  0.405940
                      Denmark        Aarhus            NaN  0.354167
                      United Kingdom Aberdeen          NaN  0.316830
North America         United States  Abilene           NaN  0.009901
...                                                    ...       ...
East Asia and Pacific China          Zhuzhou           NaN  0.420000
                                     Wenzhou           NaN  0.340000
                                     Zhongshan         NaN  0.560000
                                     Zibo              NaN  0.450000
                                     Yantai            NaN  0.090000

                                                     Bus       Car  \
region                Country        City
Europe                Germany        Aachen     0.140000  0.520000
                                     Aachen     0.128710  0.465350
                      Denmark        Aarhus     0.197917  0.447917
                      United Kingdom Aberdeen   0.178220  0.504950
North America         United States  Abilene    0.002200  0.987899
...                                                  ...       ...
East Asia and Pacific China          Zhuzhou    0.240000  0.340000
                                     Wenzhou    0.300000  0.360000
                                     Zhongshan  0.190000  0.250000
                                     Zibo       0.320000  0.230000
                                     Yantai     0.380000  0.530000

                                                        IncomeGroup  \
region                Country        City
Europe                Germany        Aachen             High income
                                     Aachen             High income
                      Denmark        Aarhus             High income
                      United Kingdom Aberdeen           High income
North America         United States  Abilene            High income
...                                                             ...
East Asia and Pacific China          Zhuzhou    Upper middle income
                                     Wenzhou    Upper middle income
                                     Zhongshan  Upper middle income
                                     Zibo       Upper middle income
                                     Yantai     Upper middle income

                                                                                  DataSource  \
region                Country        City
Europe                Germany        Aachen     The European Platform on Mobility Management
                                     Aachen                   Mobilität in Deutschland − MiD
                      Denmark        Aarhus                                      Urban Audit
                      United Kingdom Aberdeen   The European Platform on Mobility Management
North America         United States  Abilene                      US CENSUS DATA - Commuting
...                                                                                      ...
East Asia and Pacific China          Zhuzhou                                        EF CHINA
                                     Wenzhou                                        EF CHINA
                                     Zhongshan                                      EF CHINA
                                     Zibo                                           EF CHINA
                                     Yantai                                         EF CHINA

                                                                                         DataLink  \
region                Country        City
Europe                Germany        Aachen                                    https://epomm.eu/
                                     Aachen     https://www.aachen.de/de/stadt_buerger/verkehr...
                      Denmark        Aarhus     https://ec.europa.eu/eurostat/web/gisco/geodat...
                      United Kingdom Aberdeen                                  https://epomm.eu/
North America         United States  Abilene                         https://censusreporter.org/
...                                                                                           ...
East Asia and Pacific China          Zhuzhou    https://www.efchina.org/Reports-en/green-mobil...
                                     Wenzhou    https://www.efchina.org/Reports-en/green-mobil...
                                     Zhongshan  https://www.efchina.org/Reports-en/green-mobil...
                                     Zibo       https://www.efchina.org/Reports-en/green-mobil...
                                     Yantai     https://www.efchina.org/Reports-en/green-mobil...

                                                 GDPPP 2022
region                Country        City
Europe                Germany        Aachen     52745.75571
                                     Aachen     52745.75571
                      Denmark        Aarhus     67967.38187
                      United Kingdom Aberdeen   48866.60396
North America         United States  Abilene    81695.18707
...                                                     ...
East Asia and Pacific China          Zhuzhou    12614.06099
                                     Wenzhou    12614.06099
                                     Zhongshan  12614.06099
                                     Zibo       12614.06099
                                     Yantai     12614.06099

[1092 rows x 22 columns]

In [33]:
%%timeit
df['CityID'].nunique()

94 μs ± 5.53 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1092 entries, ('Europe', 'Germany', 'Aachen') to ('East Asia and Pacific', 'China', 'Yantai')
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CityID           1092 non-null   object
 1   ObsID            1092 non-null   object
 2   year             1092 non-null   int64
 3   LastObservation  1092 non-null   object
 4   metro_names      1092 non-null   object
 5   continent        1092 non-null   object
 6   subregion        1092 non-null   object
 7   state_name       1092 non-null   object
 8   state_abbr       1092 non-null   object
 9   population       1092 non-null   int64
 10  longitude        1092 non-null   float64
 11  latitude         1092 non-null   float64
 12  Walking          910 non-null    float64
 13  Cycling          910 non-null    float64
 14  Motorbykes       6 non-null      float64
 15  Active           1092 non-null   float64
 16  Bus              1092 non-null   float64
 17  Car              1092 non-null   float64
 18  IncomeGroup      1092 non-null   object
 19  DataSource       1092 non-null   object
 20  DataLink         1092 non-null   object
 21  GDPPP 2022       1092 non-null   float64
dtypes: float64(9), int64(2), object(11)
memory usage: 233.9+ KB

Correction

In [26]:
df = pd.read_csv('ModalShare.csv', 
                 engine = 'pyarrow', # Use the pyarrow engine to read faster the csv file
                 index_col=['region', 'Country', 'City']) 
df

                                                CityID   ObsID  year  \
region                Country        City
Europe                Germany        Aachen     M10001  ID0005  2003
                                     Aachen     M10001  ID0004  2017
                      Denmark        Aarhus     M10002  ID0008  2004
                      United Kingdom Aberdeen   M10003  ID0009  2008
North America         United States  Abilene    M10004    C001  2019
...                                                ...     ...   ...
East Asia and Pacific China          Zhuzhou    M10877  ID0745  2018
                                     Wenzhou    M10878  ID0746  2018
                                     Zhongshan  M10879  ID0747  2018
                                     Zibo       M10880  ID0748  2018
                                     Yantai     M10881  ID0749  2018

                                               LastObservation  \
region                Country        City
Europe                Germany        Aachen                 NO
                                     Aachen                YES
                      Denmark        Aarhus                YES
                      United Kingdom Aberdeen              YES
North America         United States  Abilene               YES
...                                                        ...
East Asia and Pacific China          Zhuzhou               YES
                                     Wenzhou               YES
                                     Zhongshan             YES
                                     Zibo                  YES
                                     Yantai                YES

                                                           metro_names  \
region                Country        City
Europe                Germany        Aachen                     Aachen
                                     Aachen                     Aachen
                      Denmark        Aarhus                     Aarhus
                      United Kingdom Aberdeen                 Aberdeen
North America         United States  Abilene    Abilene, TX Metro Area
...                                                                ...
East Asia and Pacific China          Zhuzhou                   Zhuzhou
                                     Wenzhou                   Wenzhou
                                     Zhongshan               Zhongshan
                                     Zibo                         Zibo
                                     Yantai                     Yantai

                                                    continent  \
region                Country        City
Europe                Germany        Aachen            Europe
                                     Aachen            Europe
                      Denmark        Aarhus            Europe
                      United Kingdom Aberdeen          Europe
North America         United States  Abilene    North America
...                                                       ...
East Asia and Pacific China          Zhuzhou             Asia
                                     Wenzhou             Asia
                                     Zhongshan           Asia
                                     Zibo                Asia
                                     Yantai              Asia

                                                       subregion state_name  \
region                Country        City
Europe                Germany        Aachen       Western Europe
                                     Aachen       Western Europe
                      Denmark        Aarhus      Northern Europe
                      United Kingdom Aberdeen    Northern Europe
North America         United States  Abilene    Northern America      Texas
...                                                          ...        ...
East Asia and Pacific China          Zhuzhou        Eastern Asia
                                     Wenzhou        Eastern Asia
                                     Zhongshan      Eastern Asia
                                     Zibo           Eastern Asia
                                     Yantai         Eastern Asia

                                               state_abbr  population  ...  \
region                Country        City                              ...
Europe                Germany        Aachen                    256605  ...
                                     Aachen                    256605  ...
                      Denmark        Aarhus                    331000  ...
                      United Kingdom Aberdeen                  211000  ...
North America         United States  Abilene           TX      164878  ...
...                                                   ...         ...  ...
East Asia and Pacific China          Zhuzhou                  4890000  ...
                                     Wenzhou                  1500000  ...
                                     Zhongshan                7600000  ...
                                     Zibo                     2100000  ...
                                     Yantai                   4740000  ...

                                                 Walking   Cycling  \
region                Country        City
Europe                Germany        Aachen     0.240000  0.100000
                                     Aachen     0.297030  0.108911
                      Denmark        Aarhus     0.072917  0.281250
                      United Kingdom Aberdeen   0.297030  0.019802
North America         United States  Abilene         NaN       NaN
...                                                  ...       ...
East Asia and Pacific China          Zhuzhou         NaN       NaN
                                     Wenzhou         NaN       NaN
                                     Zhongshan       NaN       NaN
                                     Zibo            NaN       NaN
                                     Yantai          NaN       NaN

                                                Motorbykes    Active  \
region                Country        City
Europe                Germany        Aachen            NaN  0.340000
                                     Aachen            NaN  0.405940
                      Denmark        Aarhus            NaN  0.354167
                      United Kingdom Aberdeen          NaN  0.316830
North America         United States  Abilene           NaN  0.009901
...                                                    ...       ...
East Asia and Pacific China          Zhuzhou           NaN  0.420000
                                     Wenzhou           NaN  0.340000
                                     Zhongshan         NaN  0.560000
                                     Zibo              NaN  0.450000
                                     Yantai            NaN  0.090000

                                                     Bus       Car  \
region                Country        City
Europe                Germany        Aachen     0.140000  0.520000
                                     Aachen     0.128710  0.465350
                      Denmark        Aarhus     0.197917  0.447917
                      United Kingdom Aberdeen   0.178220  0.504950
North America         United States  Abilene    0.002200  0.987899
...                                                  ...       ...
East Asia and Pacific China          Zhuzhou    0.240000  0.340000
                                     Wenzhou    0.300000  0.360000
                                     Zhongshan  0.190000  0.250000
                                     Zibo       0.320000  0.230000
                                     Yantai     0.380000  0.530000

                                                        IncomeGroup  \
region                Country        City
Europe                Germany        Aachen             High income
                                     Aachen             High income
                      Denmark        Aarhus             High income
                      United Kingdom Aberdeen           High income
North America         United States  Abilene            High income
...                                                             ...
East Asia and Pacific China          Zhuzhou    Upper middle income
                                     Wenzhou    Upper middle income
                                     Zhongshan  Upper middle income
                                     Zibo       Upper middle income
                                     Yantai     Upper middle income

                                                                                  DataSource  \
region                Country        City
Europe                Germany        Aachen     The European Platform on Mobility Management
                                     Aachen                   Mobilität in Deutschland − MiD
                      Denmark        Aarhus                                      Urban Audit
                      United Kingdom Aberdeen   The European Platform on Mobility Management
North America         United States  Abilene                      US CENSUS DATA - Commuting
...                                                                                      ...
East Asia and Pacific China          Zhuzhou                                        EF CHINA
                                     Wenzhou                                        EF CHINA
                                     Zhongshan                                      EF CHINA
                                     Zibo                                           EF CHINA
                                     Yantai                                         EF CHINA

                                                                                         DataLink  \
region                Country        City
Europe                Germany        Aachen                                    https://epomm.eu/
                                     Aachen     https://www.aachen.de/de/stadt_buerger/verkehr...
                      Denmark        Aarhus     https://ec.europa.eu/eurostat/web/gisco/geodat...
                      United Kingdom Aberdeen                                  https://epomm.eu/
North America         United States  Abilene                         https://censusreporter.org/
...                                                                                           ...
East Asia and Pacific China          Zhuzhou    https://www.efchina.org/Reports-en/green-mobil...
                                     Wenzhou    https://www.efchina.org/Reports-en/green-mobil...
                                     Zhongshan  https://www.efchina.org/Reports-en/green-mobil...
                                     Zibo       https://www.efchina.org/Reports-en/green-mobil...
                                     Yantai     https://www.efchina.org/Reports-en/green-mobil...

                                                 GDPPP 2022
region                Country        City
Europe                Germany        Aachen     52745.75571
                                     Aachen     52745.75571
                      Denmark        Aarhus     67967.38187
                      United Kingdom Aberdeen   48866.60396
North America         United States  Abilene    81695.18707
...                                                     ...
East Asia and Pacific China          Zhuzhou    12614.06099
                                     Wenzhou    12614.06099
                                     Zhongshan  12614.06099
                                     Zibo       12614.06099
                                     Yantai     12614.06099

[1092 rows x 22 columns]

How many distinct cities were represented in this research? Which 10 cities were surveyed the most times?
On the face of it, this doesn't seem like a particularly challenging question. But when you consider that city names repeat themselves, and that some cities were surveyed multiple times, it becomes a bit trickier.

Fortunately, the survey gives each city a unique ID number, which we can grab from the CityID column in the data frame. Counting the number of unique values of CityID will tell us how many distinct cities were included.

One option would be to take the CityID column, run drop_duplicates on its elements, and then run the count method on the results:

In [31]:
%%timeit
df['CityID'].drop_duplicates().count()

125 μs ± 3.97 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [32]:
%%timeit
len(df['CityID'].value_counts().index)

343 μs ± 38.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

$\textbf{Which 10 cities were surveyed the most times}$

Here, it was pretty clear that I would want to use value_counts. But what would I run value_counts on? And how would I then use the results?

I actually was able to run value_counts on the index itself. Index objects aren't exactly Pandas series objects, but they're not exactly not series objects, either. We can often run series methods on them, including (as is the case here) where we have a multi-index.

I thus ran value_counts on df.index. The result of value_counts is always a series in which the index contains the unique values, sorted (by default) in descending order of frequency. I can thus grab the index of that set of results to find which cities were most (and least) popular. By running head on the series, I can even get the 10 most commonly referred to cities:

In [40]:
df.index.value_counts().head(10)

(Europe, Austria, Graz)                                   8
(Europe, Austria, Vienna)                                 6
(Latin America and Caribbean, Argentina, Buenos Aires)    6
(Europe, Norway, Oslo)                                    5
(Europe, Germany, Leipzig)                                5
(Europe, Germany, Dusseldorf)                             5
(Europe, Germany, Erfurt)                                 5
(Europe, Belgium, Ghent)                                  4
(Sub-Saharan Africa, South Africa, Cape Town)             4
(Europe, United Kingdom, London)                          4
dtype: int64